### ISSUE TITLE
missing aspire.data module 

### ISSUE THREAD

**Issue by muratyesibolati** [ComputationalCryoEM/ASPIRE-Python#142]
Hi I have a trouble running  the aspire. could someone help me figure out the issue. 
it passed all tests, and I installed twice. But the problem is still there.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/exceptions.py", line 60, in handle_exception
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/__main__.py", line 14, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/commands/aspire.py", line 8, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/abinitio.py", line 15, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/utils/data_utils.py", line 9, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/utils/helpers.py", line 7, in <module>
ModuleNotFoundError: No module named 'aspire.data'

Original exception was:
Traceback (most recent call last):
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/exceptions.py", line 60, in handle_exception
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/__main__.py", line 14, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/commands/aspire.py", line 8, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/abinitio.py", line 15, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/utils/data_utils.py", line 9, in <module>
  File "/home/murat/miniconda3/envs/aspire/lib/python3.6/site-packages/aspire-0.5.28-py3.6.egg/aspire/aspire/utils/helpers.py", line 7, in <module>
ModuleNotFoundError: No module named 'aspire.data'

**Comment by junchaoxia** [comment]
This issue has be fixed in the commit 3a4f1b3 of develop branch recently and was merged to the master branch a few minutes ago, together with a few other updates.

**Comment by muratyesibolati** [comment]
okai, wonderful! I will give a try later.  Thank you very much @junchaoxia  !!!

**Comment by muratyesibolati** [comment]
thank you very much. it is working now. !
