### ISSUE TITLE
Why can't I use GPU to accelerate?

### ISSUE THREAD

**Issue by zxt-triumph** [ComputationalCryoEM/ASPIRE-Python#992]

**Comment by j-c-c** [comment]
Hi @zxt-triumph, could you provide a few more details so we can help you get up and running with the GPU?

First, would you mind sending the outputs of `pip freeze` and `nvidia-smi` so I can see what versions of dependencies you are working with? Also, have you installed one of the ASPIRE GPU extensions? You can find more information on that [here](https://computationalcryoem.github.io/ASPIRE-Python/installation.html#installing-gpu-extensions).

Thanks

**Comment by zxt-triumph** [comment]
Unable to install it successfully through the command  "cond install libblas=*=*accelerate"

**Comment by zxt-triumph** [comment]
Original exception was:
Traceback (most recent call last):
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/exceptions.py", line 87, in handle_exception
    raise exc_value
  File "gen_pro_single.py", line 63, in <module>
    src.images[:3].show()
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/source/image.py", line 99, in __getitem__
    return self.fun(indices)
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/source/simulation.py", line 270, in _images
    im = self.projections[indices]
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/source/image.py", line 99, in __getitem__
    return self.fun(indices)
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/source/simulation.py", line 243, in _projections
    im_k = self.vols[k - 1].project(rot_matrices=rot)
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/volume/volume.py", line 277, in project
    im_f[i] = nufft(data[i], pts_rot[:, i]) / self.resolution
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/nufft/__init__.py", line 226, in nufft
    plan = Plan(
  File "/home/dell/ZXT/Code/ASPIRE-Python/src/aspire/nufft/cufinufft.py", line 90, in __init__
    self._transform_plan.set_pts(*self.fourier_pts_gpu)
  File "/home/dell/anaconda3/envs/aspire_acc/lib/python3.8/site-packages/cufinufft/cufinufft.py", line 183, in set_pts
    if ky and ky.dtype != self.dtype:
  File "/home/dell/anaconda3/envs/aspire_acc/lib/python3.8/site-packages/pycuda/gpuarray.py", line 409, in __bool__
    raise ValueError("The truth value of an array with "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by j-c-c** [comment]
@zxt-triumph This error has to do with a small bug in the `cufinufft` package that was addressed in the latest release of [cufinufft v1.3](https://pypi.org/project/cufinufft/) (which will be updated in ASPIRE's next release). Upgrading your cufinufft package should resolve this.

**Comment by zxt-triumph** [comment]
Thank you for your reply and answer.
